In [148]:
#import libs
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [149]:
#read file
df=pd.read_csv("D:\\Projects\\ML\\glioma+grading+clinical+and+mutation\\dataset\\TCGA_GBM_LGG_Mutations_all.csv")

In [150]:
df

Grade   Project       Case_ID  Gender   Age_at_diagnosis  \
0     LGG  TCGA-LGG  TCGA-DU-8164    Male  51 years 108 days   
1     LGG  TCGA-LGG  TCGA-QH-A6CY    Male  38 years 261 days   
2     LGG  TCGA-LGG  TCGA-HW-A5KM    Male   35 years 62 days   
3     LGG  TCGA-LGG  TCGA-E1-A7YE  Female  32 years 283 days   
4     LGG  TCGA-LGG  TCGA-S9-A6WG    Male  31 years 187 days   
..    ...       ...           ...     ...                ...   
857   GBM  TCGA-GBM  TCGA-19-5959  Female  77 years 325 days   
858   GBM  TCGA-GBM  TCGA-16-0846    Male   85 years 65 days   
859   GBM  TCGA-GBM  TCGA-28-1746  Female  77 years 178 days   
860   GBM  TCGA-GBM  TCGA-32-2491    Male  63 years 121 days   
861   GBM  TCGA-GBM  TCGA-06-2557    Male  76 years 221 days   

           Primary_Diagnosis                       Race         IDH1  \
0     Oligodendroglioma, NOS                      white      MUTATED   
1               Mixed glioma                      white      MUTATED   
2           Astrocytoma, NOS                      white      MUTATED   
3    Astrocytoma, anaplastic                      white      MUTATED   
4    Astrocytoma, anaplastic                      white      MUTATED   
..                       ...                        ...          ...   
857             Glioblastoma                      white  NOT_MUTATED   
858             Glioblastoma                      white  NOT_MUTATED   
859             Glioblastoma                      white  NOT_MUTATED   
860             Glioblastoma                      white  NOT_MUTATED   
861             Glioblastoma  black or african american  NOT_MUTATED   

            TP53         ATRX  ...        FUBP1          RB1       NOTCH1  \
0    NOT_MUTATED  NOT_MUTATED  ...      MUTATED  NOT_MUTATED  NOT_MUTATED   
1    NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
2        MUTATED      MUTATED  ...  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
3        MUTATED      MUTATED  ...  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
4        MUTATED      MUTATED  ...  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
..           ...          ...  ...          ...          ...          ...   
857  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
858      MUTATED  NOT_MUTATED  ...  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
859      MUTATED  NOT_MUTATED  ...  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
860      MUTATED  NOT_MUTATED  ...  NOT_MUTATED      MUTATED  NOT_MUTATED   
861  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   

            BCOR        CSMD3      SMARCA4       GRIN2A         IDH2  \
0    NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
1    NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
2    NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
3    NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
4    NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
..           ...          ...          ...          ...          ...   
857  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
858  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
859  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
860  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
861  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   

            FAT4       PDGFRA  
0    NOT_MUTATED  NOT_MUTATED  
1    NOT_MUTATED  NOT_MUTATED  
2    NOT_MUTATED  NOT_MUTATED  
3        MUTATED  NOT_MUTATED  
4    NOT_MUTATED  NOT_MUTATED  
..           ...          ...  
857  NOT_MUTATED  NOT_MUTATED  
858  NOT_MUTATED  NOT_MUTATED  
859  NOT_MUTATED  NOT_MUTATED  
860  NOT_MUTATED  NOT_MUTATED  
861  NOT_MUTATED  NOT_MUTATED  

[862 rows x 27 columns]

Handeling catagegorical data 

In [151]:
df.shape

(862, 27)

In [152]:
df.isna().sum()

Grade                0
Project              0
Case_ID              0
Gender               0
Age_at_diagnosis     0
Primary_Diagnosis    0
Race                 0
IDH1                 0
TP53                 0
ATRX                 0
PTEN                 0
EGFR                 0
CIC                  0
MUC16                0
PIK3CA               0
NF1                  0
PIK3R1               0
FUBP1                0
RB1                  0
NOTCH1               0
BCOR                 0
CSMD3                0
SMARCA4              0
GRIN2A               0
IDH2                 0
FAT4                 0
PDGFRA               0
dtype: int64

In [153]:
df.isnull().sum()

Grade                0
Project              0
Case_ID              0
Gender               0
Age_at_diagnosis     0
Primary_Diagnosis    0
Race                 0
IDH1                 0
TP53                 0
ATRX                 0
PTEN                 0
EGFR                 0
CIC                  0
MUC16                0
PIK3CA               0
NF1                  0
PIK3R1               0
FUBP1                0
RB1                  0
NOTCH1               0
BCOR                 0
CSMD3                0
SMARCA4              0
GRIN2A               0
IDH2                 0
FAT4                 0
PDGFRA               0
dtype: int64

In [154]:
#drop irrelevant features
relevant_df=df.drop(['Case_ID','Project','Primary_Diagnosis','Age_at_diagnosis','Race'],axis=1)

In [155]:
relevant_df

Grade  Gender         IDH1         TP53         ATRX         PTEN  \
0     LGG    Male      MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
1     LGG    Male      MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
2     LGG    Male      MUTATED      MUTATED      MUTATED  NOT_MUTATED   
3     LGG  Female      MUTATED      MUTATED      MUTATED  NOT_MUTATED   
4     LGG    Male      MUTATED      MUTATED      MUTATED  NOT_MUTATED   
..    ...     ...          ...          ...          ...          ...   
857   GBM  Female  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED      MUTATED   
858   GBM    Male  NOT_MUTATED      MUTATED  NOT_MUTATED      MUTATED   
859   GBM  Female  NOT_MUTATED      MUTATED  NOT_MUTATED      MUTATED   
860   GBM    Male  NOT_MUTATED      MUTATED  NOT_MUTATED  NOT_MUTATED   
861   GBM    Male  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   

            EGFR          CIC        MUC16       PIK3CA  ...        FUBP1  \
0    NOT_MUTATED  NOT_MUTATED  NOT_MUTATED      MUTATED  ...      MUTATED   
1    NOT_MUTATED      MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED   
2    NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED   
3    NOT_MUTATED  NOT_MUTATED      MUTATED  NOT_MUTATED  ...  NOT_MUTATED   
4    NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED   
..           ...          ...          ...          ...  ...          ...   
857  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED   
858  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED   
859  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED   
860  NOT_MUTATED  NOT_MUTATED      MUTATED      MUTATED  ...  NOT_MUTATED   
861  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED   

             RB1       NOTCH1         BCOR        CSMD3      SMARCA4  \
0    NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
1    NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
2    NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
3    NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
4    NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
..           ...          ...          ...          ...          ...   
857  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
858  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
859  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
860      MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
861  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   

          GRIN2A         IDH2         FAT4       PDGFRA  
0    NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
1    NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
2    NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
3    NOT_MUTATED  NOT_MUTATED      MUTATED  NOT_MUTATED  
4    NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
..           ...          ...          ...          ...  
857  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
858  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
859  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
860  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
861  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  

[862 rows x 22 columns]

In [156]:
relevant_df.shape

(862, 22)

For Mapping features

In [157]:
#get number of unique attributes for features
relevant_df.describe().loc['unique']


Grade      2
Gender     3
IDH1       2
TP53       2
ATRX       2
PTEN       2
EGFR       2
CIC        2
MUC16      2
PIK3CA     2
NF1        2
PIK3R1     2
FUBP1      2
RB1        2
NOTCH1     2
BCOR       2
CSMD3      2
SMARCA4    2
GRIN2A     2
IDH2       2
FAT4       2
PDGFRA     2
Name: unique, dtype: object

Get list of unique attributes for each feature

In [158]:
for column in relevant_df.columns:
    print(column,":", relevant_df[column].unique()) 
    print(relevant_df[column].value_counts())
    print("--------------------------------------------------------------")
    

Grade : ['LGG' 'GBM']
Grade
LGG    499
GBM    363
Name: count, dtype: int64
--------------------------------------------------------------
Gender : ['Male' 'Female' '--']
Gender
Male      499
Female    359
--          4
Name: count, dtype: int64
--------------------------------------------------------------
IDH1 : ['MUTATED' 'NOT_MUTATED']
IDH1
NOT_MUTATED    448
MUTATED        414
Name: count, dtype: int64
--------------------------------------------------------------
TP53 : ['NOT_MUTATED' 'MUTATED']
TP53
NOT_MUTATED    508
MUTATED        354
Name: count, dtype: int64
--------------------------------------------------------------
ATRX : ['NOT_MUTATED' 'MUTATED']
ATRX
NOT_MUTATED    642
MUTATED        220
Name: count, dtype: int64
--------------------------------------------------------------
PTEN : ['NOT_MUTATED' 'MUTATED']
PTEN
NOT_MUTATED    718
MUTATED        144
Name: count, dtype: int64
--------------------------------------------------------------
EGFR : ['NOT_MUTATED' 'MUTATED'

In [159]:
#removing rows with '--' or unreported features
relevant_df=relevant_df.drop(relevant_df[relevant_df['Gender']=="--"].index)

In [160]:
#rechecking unique values
for column in relevant_df.columns:
    if(column=="Age_at_diagnosis"):
        continue
    print(column,":", relevant_df[column].unique()) 
    print(relevant_df[column].value_counts())
    print("--------------------------------------------------------------")
    

Grade : ['LGG' 'GBM']
Grade
LGG    498
GBM    360
Name: count, dtype: int64
--------------------------------------------------------------
Gender : ['Male' 'Female']
Gender
Male      499
Female    359
Name: count, dtype: int64
--------------------------------------------------------------
IDH1 : ['MUTATED' 'NOT_MUTATED']
IDH1
NOT_MUTATED    445
MUTATED        413
Name: count, dtype: int64
--------------------------------------------------------------
TP53 : ['NOT_MUTATED' 'MUTATED']
TP53
NOT_MUTATED    505
MUTATED        353
Name: count, dtype: int64
--------------------------------------------------------------
ATRX : ['NOT_MUTATED' 'MUTATED']
ATRX
NOT_MUTATED    639
MUTATED        219
Name: count, dtype: int64
--------------------------------------------------------------
PTEN : ['NOT_MUTATED' 'MUTATED']
PTEN
NOT_MUTATED    715
MUTATED        143
Name: count, dtype: int64
--------------------------------------------------------------
EGFR : ['NOT_MUTATED' 'MUTATED']
EGFR
NOT_MUTATED 

In [161]:
relevant_df.shape

(858, 22)

Mapping

In [162]:
#mapping others
relevant_df['Grade']=relevant_df['Grade'].map({'LGG':0,'GBM':1})
relevant_df['Gender']=relevant_df['Gender'].map({'Female':0,'Male':1})
#Mapping markers
relevant_df['IDH1']=relevant_df['IDH1'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['TP53']=relevant_df['TP53'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['ATRX']=relevant_df['ATRX'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['PTEN']=relevant_df['PTEN'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['EGFR']=relevant_df['EGFR'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['CIC']=relevant_df['CIC'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['MUC16']=relevant_df['MUC16'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['PIK3CA']=relevant_df['PIK3CA'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['NF1']=relevant_df['NF1'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['PIK3R1']=relevant_df['PIK3R1'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['FUBP1']=relevant_df['FUBP1'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['RB1']=relevant_df['RB1'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['NOTCH1']=relevant_df['NOTCH1'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['BCOR']=relevant_df['BCOR'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['CSMD3']=relevant_df['CSMD3'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['SMARCA4']=relevant_df['SMARCA4'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['GRIN2A']=relevant_df['GRIN2A'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['IDH2']=relevant_df['IDH2'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['FAT4']=relevant_df['FAT4'].map({'NOT_MUTATED':0,'MUTATED':1})
relevant_df['PDGFRA']=relevant_df['PDGFRA'].map({'NOT_MUTATED':0,'MUTATED':1})

In [163]:
relevant_df

Grade  Gender  IDH1  TP53  ATRX  PTEN  EGFR  CIC  MUC16  PIK3CA  ...  \
0        0       1     1     0     0     0     0    0      0       1  ...   
1        0       1     1     0     0     0     0    1      0       0  ...   
2        0       1     1     1     1     0     0    0      0       0  ...   
3        0       0     1     1     1     0     0    0      1       0  ...   
4        0       1     1     1     1     0     0    0      0       0  ...   
..     ...     ...   ...   ...   ...   ...   ...  ...    ...     ...  ...   
857      1       0     0     0     0     1     0    0      0       0  ...   
858      1       1     0     1     0     1     0    0      0       0  ...   
859      1       0     0     1     0     1     0    0      0       0  ...   
860      1       1     0     1     0     0     0    0      1       1  ...   
861      1       1     0     0     0     0     0    0      0       0  ...   

     FUBP1  RB1  NOTCH1  BCOR  CSMD3  SMARCA4  GRIN2A  IDH2  FAT4  PDGFRA  
0        1    0       0     0      0        0       0     0     0       0  
1        0    0       0     0      0        0       0     0     0       0  
2        0    0       0     0      0        0       0     0     0       0  
3        0    0       0     0      0        0       0     0     1       0  
4        0    0       0     0      0        0       0     0     0       0  
..     ...  ...     ...   ...    ...      ...     ...   ...   ...     ...  
857      0    0       0     0      0        0       0     0     0       0  
858      0    0       0     0      0        0       0     0     0       0  
859      0    0       0     0      0        0       0     0     0       0  
860      0    1       0     0      0        0       0     0     0       0  
861      0    0       0     0      0        0       0     0     0       0  

[858 rows x 22 columns]

Splitting the data

In [164]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(relevant_df,relevant_df.Grade,test_size=0.25,train_size=0.75, random_state=None, shuffle=True, stratify=None)
X_test=X_test.drop('Grade',axis=1)
X_train=X_train.drop('Grade',axis=1)
print("X_train\n",X_train)
print("X_test\n",X_test)
print("y_train\n",y_train)
print("y_test\n",y_test)

X_train
      Gender  IDH1  TP53  ATRX  PTEN  EGFR  CIC  MUC16  PIK3CA  NF1  ...  \
356       0     1     0     0     0     0    1      1       0    0  ...   
187       1     1     1     1     0     0    0      0       0    0  ...   
289       1     1     1     1     0     0    0      0       0    0  ...   
0         1     1     0     0     0     0    0      0       1    0  ...   
518       1     0     0     0     0     0    0      0       0    0  ...   
..      ...   ...   ...   ...   ...   ...  ...    ...     ...  ...  ...   
105       0     0     1     1     0     0    0      0       0    0  ...   
278       1     0     0     0     1     0    0      0       0    1  ...   
140       1     1     0     0     0     0    1      0       0    0  ...   
112       0     0     0     0     0     0    0      0       0    0  ...   
535       1     0     0     0     0     0    0      0       0    0  ...   

     FUBP1  RB1  NOTCH1  BCOR  CSMD3  SMARCA4  GRIN2A  IDH2  FAT4  PDGFRA  
356      0    

In [165]:
#reshaping 1d array to 2d array error: Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
y_train= y_train.values.reshape(1,-1)
y_test= y_test.values.reshape(1,-1)


In [166]:
#encoding target value because NN has 2 output class 
#from sklearn.preprocessing import OneHotEncoder
#encoder=OneHotEncoder()
#y_train=encoder.fit_transform(y_train)
#y_test=encoder.fit_transform(y_test)

Bringing data onto same scale

In [167]:
from sklearn.preprocessing import MinMaxScaler

mms=MinMaxScaler()
X_train_norm=mms.fit_transform(X_train)
X_test_norm=mms.fit_transform(X_test)
y_train_norm=mms.fit_transform(y_train)
y_test_norm=mms.fit_transform(y_test)
print("Normalized X_train\n",X_train_norm)
print("Normalized X_test\n",X_test_norm)
print("Normalized y_train\n",y_train_norm)
print("Normalized y_test\n",y_test_norm)

#from sklearn.preprocessing import MaxAbsScaler
#mas=MaxAbsScaler()
#X_train_norm=mas.fit_transform(X_train)
#X_test_norm=mas.fit_transform(X_test)
#y_train_norm=mas.fit_transform(y_train)
#y_test_norm=mas.fit_transform(y_test)


Normalized X_train
 [[0. 1. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
Normalized X_test
 [[1. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]]
Normalized y_train
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

10 fold cross validation

In [168]:
from sklearn.model_selection import StratifiedShuffleSplit
kf=StratifiedShuffleSplit(n_splits=10, test_size=0.25, train_size=0.75, random_state=None)
kf

StratifiedShuffleSplit(n_splits=10, random_state=None, test_size=0.25,
            train_size=0.75)

In [169]:
for train_index, test_index in kf.split(relevant_df,relevant_df['Grade']):
    print(train_index,test_index)

[241 135 470 613 342 376   7 750 798 743 332 639 614 205 327 343 240 631
 843 472 557 769 518 556 339 488 200 161 840  91 183 791 707 123 619 267
 355 172 531 129 779 263 128 201 362  10 276 706   1 227 759 745 676 578
 719 261 647 106  26 294 331  23 411 217 591 166 630 571 547 603 317 778
 159 367 790 121 722 753 554 517 575 535 415 727 313 402  58 697 789 346
 612 839 712 685 599 176 746 486 229 427 566 193 366 716 236 738  62 365
 461 497 824  17 708 421 652 191 615 223 841 763 514 847 361 477 475 225
 783 815  32 375 645 162 139   0 460 715 258 627 404 208  87 190 437 359
  28 549  39 195 330 252  52 133 801 787 277 610 338 211 583 703  63 657
  57 464 259 649 482 369 264 283 444 153 446 374 521 828 524 392 704 453
 633 737 213 253 295 130 324  65 141 429 233 167 669  61 775 806  82 188
 616  30 822 125 713 667 792 214 679  99 403 143 378 269 408 818 154 466
 303 780  94 770 478 384 563 640 178 827 638 632 272 582 574 360 491  59
 140 393 168 305 185 389 181 672 377 401 766 104 16

Evaluating different models

In [170]:
#importing models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

In [171]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), relevant_df,relevant_df['Grade'],cv=10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [172]:
cross_val_score(SVC(gamma='auto'),relevant_df,relevant_df['Grade'],cv=10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [173]:
cross_val_score(RandomForestClassifier(n_estimators=45), relevant_df,relevant_df['Grade'],cv=10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [174]:
cross_val_score(KNeighborsClassifier(n_neighbors=15),relevant_df,relevant_df['Grade'],cv=10)

c:\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:842: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "c:\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 140, in __call__
    score = scorer(estimator, *args, **routed_params.get(name).score)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 527, in __call__
    return estimator.score(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python311\Lib\site-packages\sklearn\base.py", line 705, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
                             ^^^^^^^^^^^^^^^
  File "c:\Python311\Lib\site-packages\sklearn\neighbors\_classification.py", line 246, in predict
    if self._fit_method == "brute" and ArgKminClassMode.is_usable_fo

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

Creating a KNN model: 

In [175]:
import torch #create tensors to store numerical values(raw data, weights, bias)
import torch.nn as nn #make weight and bias part of NN
import torch.nn.functional as F #gives activation function
import torch.optim as optim

import seaborn as sns

In [176]:
class KNN(nn.Module): #creating a new NN means creating a new class, KNN inherits from pytorch class called module
    def __init__(self, input_size, hidden_size, output_size):
        super(KNN,self).__init__()#iniitialize method for parent class nn.Module
        #Create the input layer
        self.layers=nn.ModuleList([nn.Linear(input_size,hidden_size[0])])
        #create the hidden layer
        for i in range(len(hidden_size)-1):
            self.layers.append(nn.Linear(hidden_size[i], hidden_size[i+1]))
        #create output layer
        self.layers.append(nn.Linear(hidden_size[-1],output_size))

        self.relu=nn.ReLU()

        self.float() #error: RuntimeError: Found dtype Double but expected Float (reduces efficieny because it used double)


    def forward(self,input): 
        for layer in self.layers:
            input=input.to(torch.float32)
            input=layer(input)
            input=self.relu(input)
        return input

In [177]:
#converting data set to tensor
X_test_norm_tensor=torch.tensor((X_test_norm),requires_grad=True) #requires_grad=True for optimization
X_test_norm_tensor=X_test_norm_tensor.type(torch.float32)
print("X_test",X_test_norm_tensor.size(),X_test_norm_tensor.dtype)

X_train_norm_tensor=torch.tensor((X_train_norm),requires_grad=True)
X_train_norm_tensor=X_train_norm_tensor.type(torch.float32)
print("X_train",X_train_norm_tensor.size(),X_train_norm_tensor.dtype)

y_test_norm_tensor=torch.tensor((y_test_norm),requires_grad=True)
y_test_norm_tensor=y_test_norm_tensor.type(torch.float32)
print("y_test",y_test_norm_tensor.size(),y_test_norm_tensor.dtype)

y_train_norm_tensor=torch.tensor((y_train_norm),requires_grad=True)
y_train_norm_tensor=y_train_norm_tensor.type(torch.float32)
print("y_train",y_train_norm_tensor.size(),y_train_norm_tensor.dtype)
print("-------------------------------------")
#transposing required tensors
y_test_norm_tensor=y_test_norm_tensor.transpose(0,1)
print("y_test",y_test_norm_tensor.size(),y_test_norm_tensor.dtype)
y_train_norm_tensor=y_train_norm_tensor.transpose(0,1)
print("y_train",y_train_norm_tensor.size(),y_train_norm_tensor.dtype)

X_test torch.Size([215, 21]) torch.float32
X_train torch.Size([643, 21]) torch.float32
y_test torch.Size([1, 215]) torch.float32
y_train torch.Size([1, 643]) torch.float32
-------------------------------------
y_test torch.Size([215, 1]) torch.float32
y_train torch.Size([643, 1]) torch.float32


In [178]:
input_size=21 # Number of input features
hidden_size=[20,20,20] #Number of neurons in the hidden layer
ouput_size=2 # Number of output classes

In [179]:
#creating a network
net=KNN(input_size,hidden_size,ouput_size)

In [180]:
#defining the loss function and optimizer
criterion= nn.MSELoss() # https://github.com/pytorch/pytorch/blob/main/torch/nn/functional.py#L1423 line no: 3309
optimizer=optim.SGD(net.parameters(),lr=0.01)

In [181]:
X_train=X_train_norm_tensor
y_train=y_train_norm_tensor
#training
for epoch in range(100):
    #forward pass
    outputs=net(X_train_norm_tensor)
    #compute the loss
    loss= criterion(outputs, y_train_norm_tensor)
    #back propagation and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

c:\Python311\Lib\site-packages\torch\nn\modules\loss.py:536: UserWarning: Using a target size (torch.Size([643, 1])) that is different to the input size (torch.Size([643, 2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [182]:
#save the model
torch.save(net.state_dict(),"Trained_KNN_model.pth")

Performance on Training data

In [183]:
net.eval()
with torch.no_grad():
    outputs=net(X_train_norm_tensor)
    predictions_train=torch.argmax(outputs,dim=1)

In [184]:
#comparing
counter=0
for i in range(predictions_train.size(0)):
    print("prediction",predictions_train[i],"actual",y_train_norm_tensor[i])
    if(predictions_train[i]==y_train_norm_tensor[i]):
        counter=counter+1
print("Accuracy:",(counter/predictions_train.size(0)*100))

prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn

Performance on Test data

In [185]:
#test data
net.eval()
with torch.no_grad():
    outputs=net(X_test_norm_tensor)
    predictions=torch.argmax(outputs,dim=1)

In [186]:
#comparing
counter=0
for i in range(predictions.size(0)):
    print("prediction",predictions[i],"actual",y_test_norm_tensor[i])
    if(predictions[i]==y_test_norm_tensor[i]):
        counter=counter+1
print("Accuracy:",(counter/predictions.size(0)*100))

prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn=<SelectBackward0>)
prediction tensor(0) actual tensor([0.], grad_fn